server:
  port: 8080
spring:
  application:
    name: gateway
  data:
    redis:
      host: 192.168.188.188
      port: 6379
  cloud:
    nacos:
      discovery: #注册中心相关配置
        server-addr: 192.168.188.188:8848 #默认是本地的8848(可在nacos.直接同时设置注册中心和配置中心的地址)
        cluster-name: default-cluster #可通过配置负载均衡器 实现优先选择同一集群的服务(NacosLoadBalancer)
        namespace: public #在控制台新建 用于环境隔离 不同namespace下的服务不可见
        ephemeral: true #设置为非临时实例
    sentinel:
      transport:
        dashboard: http://192.168.188.188:8858 # 设置Sentinel控制台的地址和端口
        port: 8719               # 设置与Sentinel控制台通信的端口，默认为8719
      web-context-unify: false   # 关闭上下文聚合
      http-method-specify: true # 开启请求方式前缀
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                          allowedOriginPatterns: "*"   # 允许所有来源
                          allowedMethods: "*"          # 允许所有 HTTP 方法
                          allowedHeaders: "*"          # 允许所有请求头
                          allowCredentials: false      # 不再携带 cookie（与 * 互斥）
                          maxAge: 3600                 # 预检缓存 1 小时

#jwt密钥
Jwt:
  secret:
  expiration: 60000 #分钟 测试
  renew : 5 #token续期 5分钟